### ISSUE TITLE
July 19, 2022 Meeting

### ISSUE THREAD

**Issue by dotnetdc** [dotnetdc/Open-Governance#11]
![Deploying your JS App Anywhere July 19 2022](https://user-images.githubusercontent.com/2148318/177376834-00fc0ca6-201a-4499-97f1-c76dc3169c9e.png)

## Links

* Meetup: https://www.meetup.com/dotnetdc/events/286905562/
* .NET DC YouTube: https://www.youtube.com/watch?v=B4EYSnV0-rM
* Angular DC YouTube: https://www.youtube.com/watch?v=ReiHM3i4In8
* LinkedIn: https://www.linkedin.com/video/event/urn:li:ugcPost:6947996036346908672/
* Twitch: https://www.twitch.tv/sjkilleen

## Speaker 

Alyssa Nicoll (@alyssamichelle)

## Topic 

Deploying your JS App Anywhere with .NET MAUI

## Abstract

As a JS girl in a .NET World, I have recently started learning the power of MAUI. MAUI is a .NET framework used for creating native mobile and desktop apps. I learned how to utilize a WebView inside a .NET MAUI application to wrap any sort of web app I desired (Angular, React, Vue, you name it!) and deploy it with the power of MAUI to any platform under the sun. I’m excited to show you how to do this — bridging two worlds has never been more fun!

## Bio

Sr. Developer Advocate at Progress | Angular Google Developer Expert

Alyssa is an Angular Developer Advocate for Kendo UI and a Google Developer Expert for Angular. She has spoken at over 30 conferences Internationally. She streams weekly on the Angular Air podcast and Twitch CodeItLive channel. She enjoys gaming, scuba diving, and has a little one that fondly goes by "Mr. Milks".

Pic: https://sessionize.com/image/9391-400o400o2-nC7q2babz8TWJuCMDoyW4E.png

## Before Meeting

* [x] Source speaker
* [x] Capture topic here
* [x] Add preferred bio picture
* [x] Update/Add Meetup event
* [x] Announce meetup to group
* [x] Tweet from .NET DC Twitter account
* [x] Re-tweet from personal accounts
* [x] Schedule Reminders
  * [x] dotnetdc tweets (A few days before, day before, just before)
  * [x] sean tweets (A few days before, day before, just before)
  * [x] LinkedIn messages advertising the LinkedIn event (Buffer)
* [x] Submit [form for .NET Virtual User Group](https://dotnetfoundation.org/community/virtual-user-group)
  * [x] Add blurb `This session is part of the .NET Virtual User Group(https://www.meetup.com/dotnet-virtual-user-group) series, where you can join and find more virtual user groups happening around the world.`
  * [x] Add [Virtual group slides](https://github.com/dotnet-foundation/wg-outreach/raw/master/virtual_meetup/Virtual.User.Group.Slides.pptx) to intro deck
  * [x] Add Virtual User Group link to Speaker e-mail 
* [x] Create a StreamYard event meeting/link
* [x] Add a viewing link to Meetup
* [x] Prep slide deck
* [x] Add to Excella calendar for promotion
* [x] Submit request to Excella social media for banner
* [x] Invite speaker to Meeting with StreamYard guest link
* [x] Add stream destination to .NET DC User Group YouTube
* [x] Update links to .NET DC Meetup YouTube channel
* [x] Prep icebreakers / polleverywhere polls
* [x] Upload banner images
  * [x] YouTube
  * [x] LinkedIn
  * [x] Meetup - .NET DC
  * [x] Meetup - .NET Virtual User Group
* [x] Send connection request to Speaker on LinkedIn
  * [x] Add speaker to LinkedIn event (if connected)
* [x] Publish the meetup in various channels
  * [x] DCTech Slack
  * [x] Rands Leadership Slack
  * [x] .NET Slack 
  * [x] Discords
  * [x] Women of .NET (where we were able to connect with Alyssa!)

**Comment by alyssamichelle** [comment]
# **[Deploying your JS App Anywhere with .NET MAUI](https://sessionize.com/alyssa-nicoll)**
![image](https://user-images.githubusercontent.com/1058831/173154059-03221b71-267c-460f-acb2-8c24b2789ce7.png)

**Comment by SeanKilleen** [comment]
@alyssamichelle Love it! Locking it in. I'll be in touch. 👍
