### ISSUE TITLE
September 20, 2022 Meeting

### ISSUE THREAD

**Issue by dotnetdc** [dotnetdc/Open-Governance#13]
## Would you like to speak at this meeting? We'd love to have you! Drop a comment below with some notes about what you'd like to speak on. We're happy to help you form your topic if you'd like the help!

_____

Meetup Link: TBD

## Speaker 

TBD

## Topic 

TBD

## Abstract

TBD

## Bio

TBD

Pic: TBD

## Before Meeting

* [ ] Source speaker
* [ ] Capture topic here
* [ ] Add preferred bio picture
* [ ] Update/Add Meetup event
* [ ] Announce meetup to group
* [ ] Tweet from .NET DC Twitter account
* [ ] Re-tweet from personal accounts
* [ ] Schedule Reminder tweets (A few days before, day before, just before)
  * [ ] Both Sean's account and the dotnetdc account
* [ ] Submit [form for .NET Virtual User Group](https://dotnetfoundation.org/community/virtual-user-group)
  * [ ] Add blurb `This session is part of the .NET Virtual User Group(https://www.meetup.com/dotnet-virtual-user-group) series, where you can join and find more virtual user groups happening around the world.`
  * [ ] Add [Virtual group slides](https://github.com/dotnet-foundation/wg-outreach/raw/master/virtual_meetup/Virtual.User.Group.Slides.pptx) to intro deck 
* [ ] Create a StreamYard event meeting/link
* [ ] Add a viewing link to Meetup
* [ ] Prep slide deck
* [ ] Add to Excella calendar for promotion
* [ ] Invite speaker to Meeting with StreamYard guest link
* [ ] Add stream destination to .NET DC User Group YouTube
* [ ] Update links to .NET DC Meetup YouTube channel
* [ ] Prep icebreakers / polleverywhere polls
* [ ] Upload banner images
  * [ ] YouTube
  * [ ] LinkedIn
  * [ ] Meetup - .NET DC
  * [ ] Meetup - .NET Virtual User Group
* [ ] Add speaker to LinkedIn event
* [ ] Schedule LinkedIn messages advertising the LinkedIn event (Buffer)
* [ ] Publish the meetup in various channels
  * [ ] DCTech Slack
  * [ ] Rands Leadership Slack
  * [ ] .NET Slack

**Comment by SeanKilleen** [comment]
Canceling this one to take a month off. :)
