### ISSUE TITLE
April 26, 2022 Meeting

### ISSUE THREAD

**Issue by dotnetdc** [dotnetdc/Open-Governance#8]
Meetup Link: https://www.meetup.com/dotnetdc/events/284201412/

## Topic 

Kevin Jones (@vcjones on GitHub and Twitter) 
**Title**

Everything (maybe too much) about stackalloc

**Abstract**

`stackalloc` is a keyword that has existed since C# 1.0, yet was a little-used feature. Recently it has gotten significant attention thanks to the introduction of `Span<T>` in .NET Core, largely because it offers significant performance improvements in the right circumstances. We'll be looking at `stackalloc` in-depth, not just to gain performance, but how it works, the sharp edges and security concerns that come with it, and how to avoid those concerns.

**Bio**

Kevin Jones lives in Alexandria Virginia, doing security architecture for GitHub, and helps maintain .NET's security APIs.

## Before Meeting

* [x] Source speaker
* [x] Capture topic here
* [x] Add preferred bio picture
* [x] Update/Add Meetup event
* [x] Announce meetup to group
* [x] Tweet from .NET DC Twitter account
* [x] Re-tweet from personal accounts
* [x] Schedule Reminder tweets (A few days before, day before, just before)
  * [x] Both Sean's account and the dotnetdc account
* [x] Submit [form for .NET Virtual User Group](https://dotnetfoundation.org/community/virtual-user-group)
  * [x] Add blurb `This session is part of the .NET Virtual User Group(https://www.meetup.com/dotnet-virtual-user-group) series, where you can join and find more virtual user groups happening around the world.`
  * [x] Add [Virtual group slides](https://github.com/dotnet-foundation/wg-outreach/raw/master/virtual_meetup/Virtual.User.Group.Slides.pptx) to intro deck 
* [x] Create a StreamYard event meeting/link
* [x] Add a viewing link to Meetup
* [ ] Prep slide deck
* [x] Add to Excella calendar for promotion
* [x] Invite speaker to Meeting with StreamYard guest link
* [x] Add stream destination to .NET DC User Group YouTube
* [x] Update links to .NET DC Meetup YouTube channel
* [ ] Prep icebreakers / polleverywhere polls
* [x] Upload banner images
  * [x] YouTube
  * [x] LinkedIn
  * [x] Meetup - .NET DC
  * [x] Meetup - .NET Virtual User Group
* [x] Add speaker to LinkedIn event
* [ ] Schedule LinkedIn messages advertising the LinkedIn event (Buffer)

**Comment by vcsjones** [comment]
I'll throw my hat in for speaking.

## Topic

**Title**: Everything (maybe too much) about stackalloc
**Abstract**:
`stackalloc` is a keyword that has existed since C# 1.0, yet was a little-used feature. Recently it has gotten significant attention thanks to the introduction of `Span<T>` in .NET Core, largely because it offers significant performance improvements in the right circumstances. We'll be looking at `stackalloc` in-depth, not just to gain performance, but how it works, the sharp edges and security concerns that come with it, and how to avoid those concerns.

## Bio
Kevin Jones lives in Alexandria Virginia, doing security architecture for GitHub, and helps maintain .NET's security APIs.

**Comment by vcsjones** [comment]
I am also flexible to give this talk on dates after this one. Unfortunately March is too close.

**Comment by SeanKilleen** [comment]
@vcsjones any chance you'd be good for April 26th? We had a date conflict with another user group.

**Comment by vcsjones** [comment]
@SeanKilleen sold!

**Comment by SeanKilleen** [comment]
@vcsjones awesome! Is your GitHub profile pic your preferred bio pic? If not, link me to another one. 👍 I'll get the Meetup announced ASAP.

**Comment by SeanKilleen** [comment]
Note to self: waiting on .NET VUG to make me an admin of the VUG event so I can upload an image, etc. etc.

**Comment by SeanKilleen** [comment]
Thanks again to @vcsjones for a great talk!

Archived on YouTube: https://www.youtube.com/watch?v=YjnnWbwwAkc
