### ISSUE TITLE
May 17, 2022 Meeting

### ISSUE THREAD

**Issue by dotnetdc** [dotnetdc/Open-Governance#9]
Meetup Link: https://www.meetup.com/dotnetdc/events/285707602/

## Speaker 

Chris Ayers (@codebytes)

## Topic 

Feature Flags - The Art of the IF and Deployment

## Abstract

Feature flags have gained a lot of popularity with the rise of cloud-native applications. Feature Flags help increase agility, allowing you to deploy new features into a production environment for selected users. Feature Flags allow you to release features without restarting the app or deploying new code. They separate the release of new features from their code deployment.

After this session you'll not only be able to start implementing feature flags, but you'll also want to separate your releases from your deployments. You will understand:
- What feature flags are
- The types of feature flags
- Operationalizing Feature Flags
- Best practices around feature flags
- Implementing feature flags using
- Azure Application Configuration
- Launch Darkly

## Bio

Chris is a Senior Customer Engineer on the Fast Track for Azure team at Microsoft. He has a focus in modern applications built with DevOps, microservices, containers, Single Page Apps, RESTful APIs, and cloud technologies following agile practices. In his free time, Chris is a speaker at numerous meetups, an avid reader and a gamer.

Pic: https://pbs.twimg.com/profile_images/1447673775256920066/eoilMV0b_400x400.jpg

## Before Meeting

* [x] Source speaker
* [x] Capture topic here
* [x] Add preferred bio picture
* [x] Update/Add Meetup event
* [x] Announce meetup to group
* [x] Tweet from .NET DC Twitter account
* [x] Re-tweet from personal accounts
* [x] Schedule Reminder tweets (A few days before, day before, just before)
  * [x] Both Sean's account and the dotnetdc account
* [x] Submit [form for .NET Virtual User Group](https://dotnetfoundation.org/community/virtual-user-group)
  * [x] Add blurb `This session is part of the .NET Virtual User Group(https://www.meetup.com/dotnet-virtual-user-group) series, where you can join and find more virtual user groups happening around the world.`
  * [x] Add [Virtual group slides](https://github.com/dotnet-foundation/wg-outreach/raw/master/virtual_meetup/Virtual.User.Group.Slides.pptx) to intro deck 
* [x] Create a StreamYard event meeting/link
* [x] Add a viewing link to Meetup
* [x] Prep slide deck
* [x] Add to Excella calendar for promotion
* [x] Invite speaker to Meeting with StreamYard guest link
* [x] Add stream destination to .NET DC User Group YouTube
* [x] Update links to .NET DC Meetup YouTube channel
* [x] Prep icebreakers / polleverywhere polls
* [x] Upload banner images
  * [x] YouTube
  * [x] LinkedIn
  * [x] Meetup - .NET DC
  * [x] Meetup - .NET Virtual User Group
* [x] Add speaker to LinkedIn event
* [x] Schedule LinkedIn messages advertising the LinkedIn event (Buffer)
* [x] Publish the meetup in various channels
  * [x] DCTech Slack
  * [x] Rands Leadership Slack
  * [x] .NET Slack

**Comment by AndrewTriesToCode** [comment]
Hi, I'm the creator and maintainer of a multitenant library recently accepted into the dotnet foundation.

https://www.finbuckle.com/multitenant

I'm not in the DC area currently but do you allow remote speakers? Also this would be my first time as a speaker. 

I've got two topics that I think might be of interest. 
- Multitenancy in .NET
- Automating GitHub releases - version bumps, release notes, documentation, NuGet packages, etc

Let me know what you think. 

Thanks,
Andrew

**Comment by SeanKilleen** [comment]
@AndrewTriesToCode I sincerely apologize, I'm not sure how I missed this comment while we were sourcing talks.

I just locked in a talk for May, but we'd love to have you present on either of those topics at one of our later dates. Are any of the dates on any of the other open issues workable for you? 

Again, I apologize for missing this.

**Comment by AndrewTriesToCode** [comment]
No worries, I figured I'd eventually hear from you. I'll take a look at the other dates.
